apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
  # https://artifacthub.io/packages/helm/cilium/cilium
helmCharts:
  - name: cilium
    namespace: cilium
    releaseName: ciliumrelease
    repo: https://helm.cilium.io/
    valuesFile: values.yaml
    version: 1.18.2
resources:
  - namespace.yaml
  # Gateway API stuff. Cilium currently supports 1.2, see
  # https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml

patches:
  - path: patch-delete-ca-secret.yaml
  - path: patch-delete-hubble-secret.yaml
  - path: patch-delete-hubble-relay-client-certs-secret.yaml
