apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
  # https://artifacthub.io/packages/helm/cilium/cilium
helmCharts:
  - name: cilium
    namespace: cilium
    releaseName: ciliumrelease
    repo: https://helm.cilium.io/
    valuesFile: values.yaml
    version: 1.18.0
resources:
  - namespace.yaml
patches:
  - path: patch-delete-ca-secret.yaml
  - path: patch-delete-hubble-secret.yaml
